### ISSUE TITLE
Réordonner le menu des classes à gauche

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/archipelago#10]
**Tension**
Les concepts qui sont des trucs "meta" devrait être tout en bas, les documents qui sont des objets, et non des sujets (différence conceptuelle certes mais tout de même intéressante) .. devrait être en dessous d'idées ... 

**Proposition**
Réordonner le menu : 
Acteurs
Activités
Ressources
Idées
Documents
Concepts

**Alternatives**
Une description d'alternatives auxquelles vous avez pensé.

**Comment by VincentFarcy** [comment]
PR semapps en cours : https://github.com/assemblee-virtuelle/semapps/pull/1031
Il restera à réordonner le menu d'archipelago une fois la PR validée.
