### ISSUE TITLE
Pas possible de supprimer des données importées ? 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/archipelago#110]
**Décrivez le bug**
J'aimerais enlever l'organisation [Ardear Occitanie](https://archipel.assemblee-virtuelle.org/Organization/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Forganizations%2Fardear-occitanie/show) mais je ne peux pas, je suis admin pourtant. 
Pas de bouton éditer, ni de bouton permission.

C'est une donnée que j'avais importée depuis les chemins de la transition ... Peut-être n'a t'on pas prévu le cas de supprimer une donnée importée ?

**Comment by srosset81** [comment]
Il y a une issue ici: https://github.com/assemblee-virtuelle/semapps/issues/1092
