### ISSUE TITLE
Le nombre d'items correspondant aux filtres ne s'actualise pas

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/archipelago#111]
**Décrivez le bug**
![Capture d’écran du 2023-04-14 17-11-49](https://user-images.githubusercontent.com/6160028/232083796-c897a553-f10a-417c-a2b3-2be46f0c658f.png)
Sur cette image, il devrait y avoir, à droite du filtre institution 2 items et non 0 .. 

Le bug est aussi présent sur les thèmes...

**Comment by mguihal** [comment]
Corrigé ici https://github.com/assemblee-virtuelle/semapps/pull/1179
Je me permets de clôturer
