### ISSUE TITLE
Les imports de données ne marchent plus ? 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/archipelago#149]
**Décrivez le bug**
Je ne trouve plus l'orga des Chemins de la Transition sur archipel.assemblee-virtuelle.org. Il me semble qu'on l'avait importée via le mirror mis en place.. C'est peut-être lié aux mises à jour nombreuses récemment ?

**Comment by mguihal** [comment]
Les dataServers externes ont bien été supprimé sur le repo Archipelago (https://github.com/assemblee-virtuelle/archipelago/pull/105), mais celui des Chemins de la Transition avait été remis sur l'instance de l'Assemblée Virtuelle (https://github.com/assemblee-virtuelle/deployment_semapps_av/pull/24). 

Peut-être un souci lors du déploiement ? 🤔

**Comment by srosset81** [comment]
Ping @BastienSig @simonLouvet

**Comment by simonLouvet** [comment]
@mguihal @srosset81 @GuillaumeAV , @BastienSig à vérifier que le fichier de https://github.com/assemblee-virtuelle/deployment_semapps_av/pull/24 est bien sûr le serveur. A priori, cela ne suffit pas pour assurer l'interopérabilité. Je peux enquêter sur le problème, mais pas avant le 18 décembre.

**Comment by simonLouvet** [comment]
@GuillaumeAV , @BastienSig t'apelle pour comprendre ton besoin

**Comment by simonLouvet** [comment]
@GuillaumeAV Il faut doculenter le probleme . @BastienSig n'est plus contributeur et je ne sais pas vraiment ce qui ne marche pas.

**Comment by simonLouvet** [comment]
cas d'usage :
aller sur créer une organisation et commencer à saisir
![image](https://github.com/assemblee-virtuelle/archipelago/assets/5068825/fd3f1345-a17c-48d9-9cc7-1c1ccdb0fa67)
![image](https://github.com/assemblee-virtuelle/archipelago/assets/5068825/37681997-7673-4e76-b373-16b91f3f5bcc)

Enregistrer

L'organisation apparait dans la liste des organisations et il est possible de naviguer dessus sans changer d'interface (de front)

**Comment by simonLouvet** [comment]
Cas d'usage reproductible et fonctionnel
