### ISSUE TITLE
Le nouveau DereferenceMixin ne fonctionne pas

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/archipelago#173]
Suite au déploiement de https://github.com/assemblee-virtuelle/archipelago/pull/159, lorsque j'essaie de GET un utilisateur, j'ai cette erreur:

![Capture d’écran du 2024-03-26 12-02-50](https://github.com/assemblee-virtuelle/archipelago/assets/17931931/ed30c893-1c9c-4ec1-a0a5-1e8834dbc91e)

On voit que l'erreur est générée par le DereferenceMixin, qui doit appeler `ldp.resource.get` avec un `resourceUri` vide.

En [enlevant le DerefenceMixin](https://github.com/assemblee-virtuelle/archipelago/commit/819d2eafc3ceb3c19787b8cf9af8958ff6123767) des containers /users et /organizations, ça marche à nouveau.

**Comment by simonLouvet** [comment]
la PR fonctionnait avant le deploiement de la 0.6. Je regarde

**Comment by simonLouvet** [comment]
Je n'arrive pas a reproduire en locale, tt est ok...

**Comment by simonLouvet** [comment]
Le bug venait bien d'un cas nominal non traité (pas de relations réifiées)

**Comment by srosset81** [comment]
> Le bug venait bien d'un cas nominal non traité (pas de relations réifiées sur le prédicat). Les tests automatisés sont sur semapps et pas sur archipelago. Ca pourrait être pertinent d'en ajouter, mais personne n'a la bande passante à ma connaissance

Il aurait quand même fallu tester au moins avec les données de l'AV.
