### ISSUE TITLE
Pouvoir ajouter une description à un thème

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/archipelago#24]
**Tension**
Pour l'instant, dans les thèmes, nous ne pouvons mettre qu'un titre, c'est assez frustrant.

**Proposition**
Ajouter un champ description sous le titre, qui permettrait de donner une définition plus précise du thème.
De plus, j'aimerais faire un lexique dans l'instance Meta, donc nous nous servirons de ce champ pour y mettre la définition du thème.

**Comment by GuillaumeAV** [comment]
Oui c'est une bonne idée : Dans mon idéal (SemApps v1 en l'occurence) les thèmes étaient générés via une complétion DBpedia (qui pourrait être wikidata), on récupérait du coup les abstract et tout ce qu'on voulait ...

**Comment by fluidlog** [comment]
Dupliqué par rapport à  #1

**Comment by fluidlog** [comment]
Voir #1
