### ISSUE TITLE
Le navigateur s'emballe quand on essaie d'ajouter une relation à un document

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/archipelago#41]
**Décrivez le bug**
Quand j'édite un document, "Une page web ralentit le navigateur"

**Etapes pour reproduire**
1. Aller sur un doc
2. Cliquer sur 'Editer'
3. Voir l'erreur 

Sur firefox 87.0..

**Comment by srosset81** [comment]
Fixé https://github.com/assemblee-virtuelle/archipelago/commit/e81f54f30780db17812a4bed44a630f4cbabcbe9
