### ISSUE TITLE
Problème de validation avec MarkdownInput

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/archipelago#43]
Si on passe `validate={[required()]}`, le champ doit bien être rempli pour soumettre le formulaire, mais:

- Il n'y a pas une étoile qui apparaît à côté du label
- Le label n'apparaît pas en rouge au cas où on essaie de soumettre
- Il n'y a pas de message d'erreur rouge qui apparait en-dessous

Pour faire apparaître l'étoile, on peut passer la prop `isRequired` en plus de validate (`isRequired` ne suffit pas à bloquer la soumission)

**Comment by VincentFarcy** [comment]
https://github.com/assemblee-virtuelle/semapps/pull/1028
