### ISSUE TITLE
Comportement étrange lors de l'édition du profil.

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/archipelago#49]
**Décrivez le bug**
La page de mon profil est vide
![image](https://user-images.githubusercontent.com/36893311/118687902-d30b1c00-b805-11eb-9262-9c44bc860408.png)

**Etapes pour reproduire**
Je suis connecté
Je clique sur mon nom puis "éditer mon profil"
L'écran est vide
Il faut que je clique sur un des 2 onglets pour que l'affichage se charge
![image](https://user-images.githubusercontent.com/36893311/118688058-fafa7f80-b805-11eb-8274-3be222092eb8.png)

ping @srosset81

**Comment by fluidlog** [comment]
Je reproduis en dernière version.
@srosset81 avais-tu une piste ? Penses-tu que je peux me l'affecter ? (si la piste est simple)

**Comment by srosset81** [comment]
Non pas de piste.

**Comment by fluidlog** [comment]
Lorsqu'on click sur le bouton edit sur le profil d'un utilisateur, on arrive à cette url : 
/Person/http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fyannickduthe
Si on click sur le menu en haut à droite "editer mon profil", on arrive sur l'url : 
/Person/http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fyannickduthe/edit
Et là, ça ne charge pas toute la page.
Je vais essayer de retirer le /edit dans src/frontend/packages/auth-provider/src/components/UserMenu.js
