### ISSUE TITLE
Mettre un champ Courte description sur les idées  

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/archipelago#51]
Par défaut la description longue s'affiche dans la liste ...

**Comment by fluidlog** [comment]
En effet, on voit la description longue s'afficher dans la liste : 
![image](https://user-images.githubusercontent.com/6891994/151377597-4c019102-2299-4eff-bb64-ef7d06bf7a0e.png)
J'ajoute donc un champ description courte, et j'affiche ce champ dans la liste.
Ca te va @GuillaumeAV ?

**Comment by fluidlog** [comment]
Ajout du champ dans le edit
![image](https://user-images.githubusercontent.com/6891994/151378923-e542bae3-80b0-45ff-a682-49e84be17a4d.png)

S'affiche aussi dans le show
![image](https://user-images.githubusercontent.com/6891994/151379141-34ac62e3-375d-4e1d-a807-962deb7f2d97.png)

Et dans la liste
![image](https://user-images.githubusercontent.com/6891994/151379232-b4a53c09-79b7-4c38-882f-e6ad63bec3e7.png)
