### ISSUE TITLE
Indiquer le nombre d'éléments sur les filtres

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/archipelago#7]
Les filtres sont maintenant disponibles sur la plupart des pages d'Archipel, p.ex:
https://archipel.assemblee-virtuelle.org/Organization

Cependant il serait chouette de voir le nombre d'éléments qui matchent sur le filtre, afin d'éviter de cliquer sur des filtres et d'avoir zéro résultat. 

A voir si ça peut être fait sans que ça coûte trop cher en terme de performances.

**Comment by VincentFarcy** [comment]
A clore suite  à la PR https://github.com/assemblee-virtuelle/semapps/pull/1022
Je n'ai pas les droits pour !

**Comment by VincentFarcy** [comment]
https://github.com/assemblee-virtuelle/semapps/pull/1022
