### ISSUE TITLE
Semapps n'accepte pas les URL en HTTP pour les organisations

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/archipelago#74]
**Décrivez le bug**
Si j'entre une URL en http dans le champ "Site Web" des organisations, il ajoute devant un "https".

**Etapes pour reproduire**
1. Aller sur 'une organisation'
2. Cliquer sur 'Editer'
3. Ajouter un site web en http (au lieu de https) et enregistrez
4. Retourner sur le mode présentation (show), le lien apparait bien, mais si vous mettez la souris sur le lien, vous voyez : "https://http://toto.fr" au lieu de http://toto.fr

**Comportement attendu**
Le lien devrait pouvoir pointer sur une adresse non sécurisée.

**Captures d'écran**
![image](https://user-images.githubusercontent.com/6891994/174631772-5eeefb85-3dc8-4d49-854c-3e9583168027.png)

**Comment by fluidlog** [comment]
Dans la base Jena, le lien est stocké comme ceci : 
        <http://virtual-assembly.org/ontologies/pair#homePage>
                "http://citeres.univ-tours.fr/" ;

Il contient donc le protocol (http ou https)

Par contre, si certaines URL sont stockées en base, sans le protocole, alors le navigateur ajoute le protocole et le domaine en cours, ce qui donne un lien erroné.

@srosset81 avai dû ajouter une routine pour rajouter le https, mais qui ne prenait pas en compte les sites en http.
https://github.com/assemblee-virtuelle/archipelago/blob/master/frontend/src/resources/Agent/Actor/Organization/OrganizationShow.js

J'ai donc plutôt géré le cas où il n'y avait pas de protocole.
Ca semble fonctionner en http, en https, et sans protocole (dans ce cas, j'ajoute "https://").

**Comment by srosset81** [comment]
C'est juste un problème d'affichage au niveau de ce qu'avait fait @BastienSig 
Perso je serai plutot pour utiliser le même affichage qu'OrganiGraph (https://github.com/assemblee-virtuelle/organigraph/blob/master/frontend/src/common/field/MultiUrlField.js)
