### ISSUE TITLE
Je n'arrive pas à me connceter à archipel

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/archipelago#96]
**Décrivez le bug**
Bug lors de l'authentification qui tourne en boucle sur le bouton les communs ... 
![Capture d’écran du 2022-11-01 18-10-52](https://user-images.githubusercontent.com/6160028/200600106-6a519658-c9e1-440f-b50c-afc79f2902aa.png)

**Etapes pour reproduire**
1. Sur la capture d'écran, voir que le user est data.virtual-assembly[...]guillaume.rouyer1

@srosset81 c'est le même problème que celui que rencontre @Ancelin-Moulherat-AV à priori ...

**Comment by srosset81** [comment]
C'est bon, je crois que c'est corrigé. @GuillaumeAV tu devras sans doute te reconnecter.

J'ai lancé cette commande pour effacer les doublons:

```
call ldp.resource.delete --resourceUri https://data.virtual-assembly.org/users/srosset811 --webId system
call ldp.resource.delete --resourceUri https://data.virtual-assembly.org/users/guillaume.rouyer1 --webId system
call ldp.resource.delete --resourceUri https://data.virtual-assembly.org/users/yannickduthe1 --webId system
call ldp.resource.delete --resourceUri https://data.virtual-assembly.org/users/simon.louvet.zen1 --webId system
call ldp.resource.delete --resourceUri https://data.virtual-assembly.org/users/alice.poggioli1 --webId system
call ldp.resource.delete --resourceUri https://data.virtual-assembly.org/users/v.farcy721 --webId system
call ldp.resource.delete --resourceUri https://data.virtual-assembly.org/users/jules.lecuir1 --webId system
call ldp.resource.delete --resourceUri https://data.virtual-assembly.org/users/bastien.siguier1 --webId system
call ldp.resource.delete --resourceUri https://data.virtual-assembly.org/users/ancelinmoulherat --webId system
call ldp.resource.delete --resourceUri https://data.virtual-assembly.org/users/sebastien.rosset1 --webId system
```

Puis j'ai mis à jour le dataset `settings` pour qu'il ne pointe pas vers les ressources qui finissent par "1".
Finalement j'ai effacé le cache Redis pour être sûr.
