### ISSUE TITLE
Ajouter un champ description sur les personnes 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/archipelago#99]
**Tension**
Je peux pas mettre ma bio et mon CV extraordinaire !

**Proposition**
Ajouter simplement un champ texte Description sur les personnes, facile non @srosset81 / @BastienSig / @simonLouvet  ? 

**Alternatives**
Me vendre sur facebook !

**Comment by rmkni** [comment]
Could we use the data property [description](https://virtual-assembly.org/ontologies/pair-2021-summer/index-en.html#description) on all Actor objects? Today is seems only available for organisations but not on people and groups.

**Comment by srosset81** [comment]
Yes I think this is what is proposed on this issue !
